### ISSUE TITLE
error : UnhandledPromiseRejectionWarning: RequestError: Error: read ECONNRESET

### ISSUE THREAD

**Issue by rsa408** [tahuja3482/instagram-utility-tool#1]
Hello Guys,

When I run this code most of the time I get the following error, what I find is that this error occurs during the line of await client.login();

```
(node:6032) UnhandledPromiseRejectionWarning: RequestError: Error: read ECONNRESET
    at new RequestError (D:\insta\newp\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\insta\newp\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\insta\newp\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\insta\newp\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (D:\insta\newp\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks for your code and your help.

**Comment by tahuja3482** [comment]
This could possible be an IP ban issue. Try using the latest commit with a VPN. And I'll try to add some handling on the next commit.

**Comment by rsa408** [comment]
Yes, it Worked. Thank you so much.
just one more question how can I retrieve over 10k or 20k followers or followings list? 
Also How can prevent it for several requests? Should I change IP in every request?
Regards
